name: budget-app-dev

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
      target: development-dependencies-env
    container_name: dev-budget-app-webapp
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 5000:5000
      - 5001:5001
    depends_on:
      - budget-app-db
    command: ["pnpm", "dev"]
  budget-app-db:
    image: mongo:8.0.6
    container_name: dev-budget-app-db
    volumes:
      - budget-app-db-data:/data/db
    ports:
      - 27017:27017
    env_file:
      - ./apps/budget-app-backend/.env

volumes:
  budget-app-db-data:
