name: budget-app-prod

services:
  budget-app-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    container_name: prod-budget-app-frontend
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - budget-app-backend
    env_file:
      - ./apps/budget-app-frontend/.env
  budget-app-backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    container_name: prod-budget-app-backend
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - budget-app-db
    env_file:
      - ./apps/budget-app-backend/.env
  reverse-proxy:
    image: nginx:stable-alpine3.20
    container_name: prod-budget-app-reverse-proxy
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 7003:80
    depends_on:
      - budget-app-frontend
      - budget-app-backend
