name: budget-app-dev

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
      target: development-dependencies-env
    container_name: dev-budget-app-webapp
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - budget-app-db
    command: ["pnpm", "dev"]
  budget-app-db:
    image: mongo:8.0.6
    container_name: dev-budget-app-db
    volumes:
      - budget-app-db-data:/data/db
    ports:
      - 27017:27017
    env_file:
      - ./apps/budget-app-backend/.env
  reverse-proxy:
    image: nginx:stable-alpine3.20
    container_name: dev-budget-app-reverse-proxy
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 3000:80
    depends_on:
      - webapp

volumes:
  budget-app-db-data:
