services:
  budget-app-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    container_name: prod-budget-app-frontend
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 5001:5001
    depends_on:
      - budget-app-backend
      - budget-app-db
    env_file:
      - ./apps/budget-app-frontend/.env
  budget-app-backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    container_name: prod-budget-app-backend
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 5000:5000
    depends_on:
      - budget-app-db
    env_file:
      - ./apps/budget-app-backend/.env
  budget-app-db:
    image: mongo:8.0.6
    container_name: prod-budget-app-db
    volumes:
      - budget-app-db-data:/data/db
    ports:
      - 27017:27017
    env_file:
      - ./apps/budget-app-backend/.env

volumes:
  budget-app-db-data:
