name: budget-app-prod

services:
  budget-app-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    container_name: prod-budget-app-frontend
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 7001:7001
    depends_on:
      - budget-app-backend
    env_file:
      - ./apps/budget-app-frontend/.env
  budget-app-backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    container_name: prod-budget-app-backend
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 7000:7000
    depends_on:
      - budget-app-db
    env_file:
      - ./apps/budget-app-backend/.env
  # TODO: Remove this service because will use a real database for production
  budget-app-db:
    image: mongo:8.0.6
    container_name: prod-budget-app-db
    volumes:
      - budget-app-db-data:/data/db
    ports:
      - 27018:27017
    env_file:
      - ./apps/budget-app-backend/.env

volumes:
  budget-app-db-data:
