services:
  budget-app-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development-dependencies-env
    container_name: dev-budget-app-frontend
    volumes:
      - ./:/app/dev-budget-app-frontend
      - /app/node_modules
    ports:
      - 5001:5001
    depends_on:
      - budget-app-backend
      - budget-app-db
    env_file:
      - ./apps/budget-app-frontend/.env
    command: ["pnpm", "dev:frontend"]
  budget-app-backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development-dependencies-env
    container_name: dev-budget-app-backend
    volumes:
      - ./:/app/dev-budget-app-backend
      - /app/node_modules
    ports:
      - 5000:5000
    depends_on:
      - budget-app-db
    env_file:
      - ./apps/budget-app-backend/.env
    command: ["pnpm", "dev:backend"]
  budget-app-db:
    image: mongo:8.0.6
    container_name: dev-budget-app-db
    volumes:
      - budget-app-db-data:/data/db
    ports:
      - 27017:27017
    env_file:
      - ./apps/budget-app-backend/.env

volumes:
  budget-app-db-data:
